#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-1} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

if [[ $DISTRO_NAME =~ (ubuntu|debian)$ ]]; then
    apt-get install -y chrony
elif [[ $DISTRO_NAME =~ (centos|rocky|rhel|openeuler)$ ]]; then
    dnf install -y chrony
else
    echo "The 'chrony' element does not support this distribution."
    echo "Exiting"
    exit 1
fi

systemctl enable chronyd
