#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-1} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

case "$DIB_INIT_SYSTEM" in
systemd)
    if [ -f "/usr/sbin/firewalld" ]; then
        systemctl disable firewalld.service
    elif [ -f "/usr/sbin/ufw" ]; then
        systemctl disable ufw.service
    fi
    ;;
esac
